name: Scheduled Retrain

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install pipenv and dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Retrain model
        run: pipenv run python train.py

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-joblib
          path: model.joblib

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-metrics
          path: training_metrics.json
